### ISSUE TITLE
Yoast by Breadcrumbs is reflecting Home Two times.

### ISSUE THREAD

**Issue by syedimran22** [ahmedkaludi/accelerated-mobile-pages#2439]
Desc: Yoast by Breadcrumbs option is reflecting Home Two times.
Ref: https://secure.helpscout.net/conversation/634395015/31475?folderId=2169251
Screenshot: http://take.ms/CsZOD

**Comment by Zabi09** [comment]
This problem was from the Yoast SEO plugin and it was fixed by the user, so closing this ticket by approval of @ahmedkaludi

**Comment by whiwo** [comment]
Nope, this is not a problem with the Yoast plugin. The %category% showing up in the file name was the Yoast plugin issue but the breadcrumbs via Yoast works perfectly in desktop mode but in AMP mode the "Home" link shows up twice. That issue has still not been resolved. It's definitely affecting the sitelinks for the site. Without the proper structure for the breadcrumbs, Google does not recognize the tree.
