### ISSUE TITLE
Conflicts with themes using redux framework and throws errors 

### ISSUE THREAD

**Issue by yawalkar** [ahmedkaludi/accelerated-mobile-pages#246]
I just installed the plugin and got these errors on activation. It does conflicts with the themes using redux framework and also using TGM. Please fix it asap.

### Errors - 

Notice: Use of undefined constant AMP_QUERY_VAR - assumed 'AMP_QUERY_VAR' in /Applications/XAMPP/xamppfiles/htdocs/avada/wp-content/plugins/amp/includes/amp-helper-functions.php on line 42

Notice: Undefined index: type in /Applications/XAMPP/xamppfiles/htdocs/dev/wp-content/plugins/accelerated-mobile-pages/includes/options/redux-framework/framework.php on line 1226

Notice: Undefined index: type in /Applications/XAMPP/xamppfiles/htdocs/dev/wp-content/plugins/accelerated-mobile-pages/includes/options/redux-framework/framework.php on line 1231

Notice: Undefined index: type in /Applications/XAMPP/xamppfiles/htdocs/dev/wp-content/plugins/accelerated-mobile-pages/includes/options/redux-framework/framework.php on line 1146

Notice: Undefined index: type in /Applications/XAMPP/xamppfiles/htdocs/dev/wp-content/plugins/accelerated-mobile-pages/includes/options/redux-framework/framework.php on line 1147

Notice: Undefined index: type in /Applications/XAMPP/xamppfiles/htdocs/dev/wp-content/plugins/accelerated-mobile-pages/includes/options/redux-framework/framework.php on line 1153

Notice: Undefined index: type in /Applications/XAMPP/xamppfiles/htdocs/dev/wp-content/plugins/accelerated-mobile-pages/includes/options/redux-framework/framework.php on line 1174

http://prntscr.com/ddjwyq

**Comment by yawalkar** [comment]
Not sure if you guys are taking it on serious note, I just updated the plugin to the latest version, and found that the notices are still there. Tried to use the builder, and this is what I see in the customizer - <img src="http://image.prntscr.com/image/50f2d7232c454fa6b7e67dba21ed29e7.png">

**Comment by khaledMohammed000** [comment]
@yawalkar Sorry for the inconvenience we are trying are best ... we will sort this out ASAP

**Comment by ahmedkaludi** [comment]
@yawalkar  Can you tell me which theme are you using? I guess it is conflicting with the theme?

**Comment by yawalkar** [comment]
@ahmedkaludi These errors aren't theme / plugin specific. I tried this on twenty sixteen default theme too. I have WP_DEBUG set to true always as every developer should do. Please check the plugin with WP_DEBUG true. The plugin must not produce any errors or warnings if you have the debug mode ON.

**Comment by MohammedKaludi** [comment]
all redux related warnings fixed. Customizer warnings are still showing but will need to debug in parent plugin to fix this issue. As it is coming from Parent AMP plugin as well.

New ticket created for Customizer warnings https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/406
