### ISSUE TITLE
Pagination issue

### ISSUE THREAD

**Issue by Lofesa** [ahmedkaludi/accelerated-mobile-pages#388]
Hi to all
In desing-manager/desing-X/index.php you use the functions next_posts_link and previous_posts_link (lines 79-80 in desing-1 and lines 77-78 in desing-2 in master branch at 8-Jan-2016). These functions return relative url like href="page/2/" and the absolute url become http://www.example.com/amp/page/2/ that can´t work and the list of post viewed never change.

I have tried to manualy use of these url http://www.example.com/page/2/amp/ and get 404 error but url http://www.example.com/page/2/?amp work well

**Comment by ahmedkaludi** [comment]
We have fixed this issue in the recent 0.9.33 update with a rewrite code

**Comment by Lofesa** [comment]
The issue is not solved in 0.9.33 as you can see [here](https://intersindical.intersindicalrm.org/amp/)
The "next" button is `<div class=next><a href="page/2/">Siguiente &raquo;</a></div>` and the url don´t work.
As far I can see only work page/2/?amp

**Comment by khaledMohammed000** [comment]
@Lofesa 

Please resave the permalinks and check and let us know if this still persists 👍

**Comment by Lofesa** [comment]
resaved permalinks, issue persists as you can se [here](https://spublicos.intersindicalrm.org/amp/) or [here](http://www.inmeteo.net/blog/amp/).
Rewrite rule from ampforwp_add_custom_rewrite_rules() don´t work for this, I dont know why.
The next_posts_link() function in index.php (on both desings) returns http://site/amp/page/2 (in the next button on index page) and this make you never go from index page the url that seems to work is http://site/page/2/?amp

**Comment by Lofesa** [comment]
@khaledMohammed000 
to review PR  Pagination issue on next button #421

**Comment by ahmedkaludi** [comment]
We have properly fixed this issue in 0.9.40 update. It must work properly now.

**Comment by Lofesa** [comment]
hi @ahmedkaludi @khaledMohammed000 
This issue is related to [#449](https://github.com/ahmedkaludi/accelerated-mobile-pages/issues/449).
Updated to 0.9.40, resaved permalinks... and still here

**Comment by ahmedkaludi** [comment]
@MohammedKaludi Please review this once

**Comment by MohammedKaludi** [comment]
@ahmedkaludi this has been fixed and properly working on one of the above-given sites. You can test by visiting https://spublicos.intersindicalrm.org/page/4/amp/ 

Closing the ticket.
