### ISSUE TITLE
Scrolling in iframe (Disqus)

### ISSUE THREAD

**Issue by ahmedkaludi** [ahmedkaludi/accelerated-mobile-pages#566]
See: https://wordpress.org/support/topic/cant-scroll-disqus-comments/

**Comment by khaledMohammed000** [comment]
done here https://github.com/ahmedkaludi/accelerated-mobile-pages/commit/19d62661161e43e26f4858ec77f41a079ed655f9

**Comment by MohammedKaludi** [comment]
Working smoothly

**Comment by danielcardoso5** [comment]
Hi @ahmedkaludi, the issue #534 was not addressed.

Here you can see an embed code with responsive support:

`<amp-iframe src="https://primetag2.azureedge.net/embed/collage.html?slug=v08d8pWv6&owner=13" layout="responsive" sandbox="allow-scripts allow-popups allow-same-origin" resizable frameborder="0" width="320" height="100"><amp-img layout="fill" src="//primetag2.azureedge.net/static/graphics/images/placeholders/amp-placeholder.png" placeholder></amp-img><div overflow tabindex="0" role="button" aria-label="Expand" style="position:relative;font-family:Lato,Helvetica,Arial,sans-serif;text-align:center;background-color:rgba(245,245,245,0.8);font-size:20px;line-height:24px;color:#777;">&dtrif;</div></amp-iframe><span style="display:none;"><script async src="https://cdn.ampproject.org/v0/amp-iframe-0.1.js"></script></span>
`

By placing this code on a page with the AMP main script, it should render the iframe correctly. The problem is that wordpress removes the div with overflow attribute. You can test on a Blogger powered blog. The amp-img is necessary in order for the iframe to be shown above the fold.

**Comment by vlrevolution** [comment]
This issue is still present and keeping us from using amp-iframe. Please can you give me some advice on how to fix this? It is such a complex plugin and I am having a hard time figuring it out myself. We need resizable to work.

Maybe you can get some ideas from here:
https://github.com/ampproject/amp-wp/commit/c46532aad0070f36ed5bbc7918ecbd7a9c86f335#diff-3933722cc42f50f1ff2d283a331c7c98a77a26152cd1f42a36bde5562adf129b
